Updated espocrm for 16.1
turnkeylinux-apps/espocrm pull request #16
Opened 2021-02-08 05:06 UTC by OnGle

Closes https://github.com/turnkeylinux/tracker/issues/1363

2021-02-08 05:17 UTC, OnGle commented
Oops forgot the espocrm-websockets unit file (now included)

2021-02-10 02:42 UTC, JedMeister requested changes
Could you please just add a note re the closed issue to the changelog? Thanks in anticipation... :smile:

2021-02-10 02:42 UTC, JedMeister commented on changelog
> +
Would be good to also note the inclusion of the websocket (and that it closes issue XXX) plus also note the new requirement for a domain.

2021-02-10 03:59 UTC, OnGle commented on changelog
> +
No worries, please see the 2 additional commits

2021-02-10 04:35 UTC, merged